version: '3.8'

services:
  iqa-app:
    build: .
    container_name: iqa-app
    ports:
      - "4001:80"
    restart: unless-stopped
    networks:
      - coolify # สั่งให้เข้าไปอยู่ในวง Network หลักของ Coolify

networks:
  coolify:
    external: true # บอกว่า Network นี้ถูกสร้างไว้แล้ว(โดย Coolify) ไม่ต้องพยายามสร้างใหม่
