version: '3.8'

services:
  iqa-app:
    build: .
    container_name: iqa-app
    ports:
      - "4001:4001"
    restart: unless-stopped
    networks:
      - coolify

networks:
  coolify:
    external: true
