version: '3.8'

services:
  iqa-app:
    build: .
    container_name: iqa-app
    labels:
      - traefik.enable=true
      - traefik.http.routers.iqa-app.rule=Host(`iqa.rslhub.me`)
      - traefik.http.services.iqa-app.loadbalancer.server.port=4001
    restart: unless-stopped
    networks:
      - coolify

networks:
  coolify:
    external: true
